//Generic Dimension
// ignore_for_file: constant_identifier_names

const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2x = 16.0;
const MARGIN_MEDIUM_3x = 20.0;

const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2x = 16.0;
const TEXT_REGULAR_3x = 20.0;
const TEXT_HEADING = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;

//app specific
const APPBAR_ELEVATION = 0.0;
const BANNER_HEIGHT = 200.0;
const PLAYBUTTON_SIZE = 56.0;
const MOVIE_LIST_HEIGHT = 300.0;
const MOVIE_LIST_ITEM_WIDTH = 160.0;
const MOVIE_VIEW_HEIGHT = 200.0;
const MOVIE_SHOWTIME_HEIGHT = 180.0;
const SHOWCASE_HEIGHT = 200.0;
const SHOWCASE_WIDTH = 300.0;
const MOVIE_DETAILS_SCREEN_SLIVER_APP_BAR_HEIGHT = 300.0;
const MOVIE_DETAILS_SCREEN_APP_BAR_FONT_SIZE = 56.0;
