const HOMEPAGE_APPBAR_TITLE = 'Discover';
const HOMEPAGE_BEST_POPULAR_FILMS_AND_SERIALS = 'BEST POPULAR FILMS AND SERIALS';
const HOMEPAGE_CHECK_MOVIE_SHOW_TIME = 'Check Movie\nShowtimes';
const HOMEPAGE_SEE_MORE = 'SEE MORE';
const SHOWCASE_TITLE = 'SHOWCASES';
const SHOWCASE_SEE_MORE = 'MORE SHOWCASES';
const BEST_ACTOR_TITLE = 'BEST ACTORS';
const BEST_ACTOR_SEE_MORE = 'MORE ACTORS';

const MOVIE_DETAIL_SCREEN_ACTORS_SECTION_TITLE = 'ACTORS';
const MOVIE_DETAIL_SCREEN_CREATORS_SECTION_TITLE = 'CREATORS';
const MOVIE_DETAIL_SCREEN_CREATORS_SECTION_SEE_MORE = 'MORE CREATORS';
const MOVIE_DETAIL_SCREEN_STORYLINE_TITLE = 'STORYLINE';

const MOVIE_DETAIL_SCREEN_PLAY_TRAILER_BUTTON_TEXT = 'PLAY TRAILER';
const MOVIE_DETAIL_SCREEN_RATE_MOVIE_BUTTON_TEXT = 'RATE MOVIE';
const MOVIE_DETAIL_SCREEN_ABOUT_FILM_TITLE= 'ABOUT FILM';