const int HIVE_TYPE_ID_ACTOR_VO = 1;
const int HIVE_TYPE_ID_COLLECTION_VO = 2;
const int HIVE_TYPE_ID_COUNTRY_VO = 3;
const int HIVE_TYPE_ID_DATE_VO = 4;
const int HIVE_TYPE_ID_GENRE_VO = 5;
const int HIVE_TYPE_ID_MOVIE_VO = 6;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO = 7;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 8;